services:
  serve-model:
    image: ghcr.io/release-engineering-group-13/model-service:latest 
    ports:
      - 8080:8080
    volumes:
      - ./model:/root/model/
    networks:
      - default-network
    extra_hosts:
      - "host.docker.internal:host-gateway"


networks:
  default-network:
    driver: bridge